#!/bin/sh
# Ensure the discriminator in sort works

# Copyright (C) 2010-2011 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. "${srcdir=.}/init.sh"; path_prepend_ ../src
print_ver_ sort

# Set limit variables
LC_ALL=C getlimits_

  printf -- "\
abcdefghijklm
nopqrstuvwxyz
" > exp
  tac exp | sort -R --random-source=exp | sort > out || fail=1

  compare out exp || fail=1

  printf -- "\
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaae
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaf
" > exp

  tac exp | sort -R --random-source=exp | sort > out || fail=1

  compare out exp || fail=1

  printf -- "\
$INTMAX_UFLOW
$INTMAX_MIN
0
$INTMAX_MAX
$INTMAX_OFLOW
" > exp

  tac exp | sort -R --random-source=exp | sort -n > out || fail=1

  compare out exp || fail=1

nmax=`expr $INTMAX_MAX / 100`
nmax_minus_1=`expr $nmax - 1`
  printf -- "\
-$nmax
-$nmax_minus_1.9
-$nmax_minus_1.8
-$nmax_minus_1.7
-$nmax_minus_1.6
-$nmax_minus_1.5
-$nmax_minus_1.4
-$nmax_minus_1.3
-$nmax_minus_1.2
-$nmax_minus_1.1
-$nmax_minus_1
0
$nmax_minus_1
$nmax_minus_1.1
$nmax_minus_1.2
$nmax_minus_1.3
$nmax_minus_1.4
$nmax_minus_1.5
$nmax_minus_1.6
$nmax_minus_1.7
$nmax_minus_1.8
$nmax_minus_1.9
$nmax
" > exp

  tac exp | sort -R --random-source=exp | sort -n > out || fail=1

  compare out exp || fail=1

  printf -- "\
$INTMAX_UFLOW
$INTMAX_MIN
0
$INTMAX_MAX
$INTMAX_OFLOW
" > exp

  tac exp | sort -R --random-source=exp | sort -h > out || fail=1

  compare out exp || fail=1

hmax=`expr $INTMAX_MAX / 10`
hmax_minus_1=`expr $hmax - 1`
  printf -- "\
-$hmax
-$hmax_minus_1.9
-$hmax_minus_1.8
-$hmax_minus_1.7
-$hmax_minus_1.6
-$hmax_minus_1.5
-$hmax_minus_1.4
-$hmax_minus_1.3
-$hmax_minus_1.2
-$hmax_minus_1.1
-$hmax_minus_1
0
$hmax_minus_1
$hmax_minus_1.1
$hmax_minus_1.2
$hmax_minus_1.3
$hmax_minus_1.4
$hmax_minus_1.5
$hmax_minus_1.6
$hmax_minus_1.7
$hmax_minus_1.8
$hmax_minus_1.9
$hmax
" > exp

  tac exp | sort -R --random-source=exp | sort -h > out || fail=1

  compare out exp || fail=1

Exit $fail
